Add Individuals from the UI
chaoss/grimoirelab-sortinghat pull request #387
Opened 2020-11-10 13:29 UTC by evamillan

Adds the `ProfileModal` component, which displays a form that allows a new individual to be created. The component
uses three Apollo mutations, passed as props, to create the individual, update their profile information and enroll them in organizations. The modal is added inside `IndividualsTable` and can be opened clicking the "add" button.

2020-11-10 17:44 UTC, sduenas requested changes
In general, the PR looks good to me but it needs some changes before we merged it:

- The only required argument in the form should be the `source` but the user should provide at least one of `name`, `email`, or `username` to create the new identity.
- The dates should be given using the format YYYY-MM-DD. This format doesn't create problems trying to understand where the month or the day goes. Also, I wonder if make sense to use a date picker for the ranges.
- For the country code, we can use a list of countries instead. Not sure if we can pre-loaded somehow but the ideal would be to load it from SortingHat.

2020-11-12 10:40 UTC, evamillan commented
I updated the PR with the changes you requested. Since the individual's name and email are not required, I had to change the cards and table entries a bit too so they weren't completely empty. 

![imagen](https://user-images.githubusercontent.com/26812577/98929593-aa633c00-24db-11eb-86fe-03bcd296eb75.png)

2020-11-12 11:05 UTC, sduenas commented
> I updated the PR with the changes you requested. Since the individual's name and email are not required, I had to change the cards and table entries a bit too so they weren't completely empty.
> 
> ![imagen](https://user-images.githubusercontent.com/26812577/98929593-aa633c00-24db-11eb-86fe-03bcd296eb75.png)

Individuals `name` field will be always available because it's part of the profile. When a new individual is created, the server assigns a name based on the fields that were given. If no name was given, the value will be an email or a username but it will be stored under `name`.

Having said that, I don't think you need the part of the code where you treat that. You just need to take `name` form the profile and show it in the card.

2020-11-12 11:38 UTC, sduenas requested changes
The Individual can't be added if a country is not given. Also, check my other comments.

2020-11-12 11:38 UTC, sduenas commented on ui/src/components/IndividualCard.vue
> +      let initials = names[0].substring(0, 1).toUpperCase();
As I explained in my comment before, this isn't needed. The code should take the field `name` from the profile, not from the identities.

2020-11-12 11:38 UTC, sduenas commented on ui/src/components/IndividualEntry.vue
> +      let initials = names[0].substring(0, 1).toUpperCase();
Same comment as in the card component.

2020-11-12 12:13 UTC, evamillan commented
I fixed the error when no country is selected and changed the card and entry code according to your comments.

2020-11-12 12:48 UTC, sduenas approved these changes
LGTM

2020-11-12 12:49 UTC, merged