[ui] Remove individuals affiliations
chaoss/grimoirelab-sortinghat pull request #404
Opened 2020-11-23 15:48 UTC by evamillan

This PR adds the `withdraw` Apollo mutation, which removes an individual's affiliation to an organization.
An individual's affiliation can be removed by clicking the delete button next to it on `ExpandedIndividual`.

2020-11-24 13:57 UTC, sduenas requested changes
Please check my comment. The rest of the PR looks good to me.

2020-11-24 13:57 UTC, sduenas commented on ui/src/apollo/mutations.js
> +const withdraw = (apollo, uuid, organization) => {
This mutation must also get the period of time to remove. Remember that an Individual could be affiliated to the same organization during different periods of time.

2020-11-24 15:20 UTC, evamillan commented
Thank you, I updated the PR.

2020-11-25 18:21 UTC, sduenas approved these changes
LGTM

2020-11-25 18:23 UTC, merged