[ui] Individuals search box
chaoss/grimoirelab-sortinghat pull request #408
Opened 2020-11-27 11:59 UTC by evamillan

This PR adds the `Search` component, which offers hints of the available filters and syntax to users as they type. So far, the available filters are `term` and `lastModified`. The search value is then parsed and emitted to the parent component `IndividualsTable` to perform the query.

Vuetify is upgraded to version ^2.3.19 to solve an issue with  the `v-combobox` component used on the search. Some components and CSS classes had been deprecated, so they have been updated.

Note: running a query with the lastModify filter will throw an error until the server part is ready.

2020-12-02 11:49 UTC, evamillan commented
I updated the PR. I added tests and fixed some issues on the Search component that I noticed while testing.

2020-12-10 14:39 UTC, sduenas requested changes
The PR looks good to me but there are some minor comments.

2020-12-10 14:39 UTC, sduenas commented on ui/tests/unit/queries.spec.js
> +  ])("Given an invalid value renders an error", async (value) => {
I think there must be a test case where `lastUpdated` has two operators. It should return an error too. For example `lastUpdated:>=2000-01-01<=2000-01-01` or `lastUpdated:===2000-01-01`.

2020-12-10 14:39 UTC, sduenas commented on ui/tests/unit/queries.spec.js
>    test.each([
I think these tests should be in a different file. These are the tests for the queries.

2020-12-10 16:26 UTC, evamillan commented
I added the test cases and moved them to a separate file.

2020-12-10 16:37 UTC, sduenas approved these changes
LGTM

2020-12-10 16:39 UTC, merged