Improve style of the IdentityCard expanded view
chaoss/grimoirelab-sortinghat pull request #443
Opened 2021-02-09 10:35 UTC by evamillan

This PR moves the identities and organizations data in the compact view of `ExpandedIndividual` to Vuetify simple tables to
improve readability. The data sources are replaced with their icon to save space.

This is an example of the improved view:
![imagen](https://user-images.githubusercontent.com/26812577/107351209-9fb04700-6aca-11eb-86fa-6da1e33c4d43.png)

2021-02-09 16:13 UTC, sduenas requested changes
Looks great but I have some comments.

2021-02-09 16:13 UTC, sduenas commented on ui/.storybook/preview-head.html
> +<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
Can we change this to static fonts? There are some concerns about GDPR and Google Fonts.

https://complianz.io/google-fonts-and-gdpr-does-it-work/

2021-02-09 16:13 UTC, sduenas commented on ui/src/components/ExpandedIndividual.vue
> +            <td><v-icon v-text="item.icon" small left /></td>
Is it possible to add the name of the source when the cursor is over the icon?

2021-02-15 10:57 UTC, evamillan commented
@sduenas I added the fonts to the project assets, the app was also loading them from Google Fonts. I also added the name of the source to the icons.

2021-02-15 12:59 UTC, sduenas approved these changes
LGTM

2021-02-15 13:01 UTC, merged