Search bot individuals
chaoss/grimoirelab-sortinghat pull request #461
Opened 2021-02-24 10:56 UTC by evamillan

Adds the `isBot` filter to the individuals query, which accepts a boolean value and returns a list of individuals filtered by their bot status.

2021-02-24 13:10 UTC, sduenas requested changes
Please check my review.

2021-02-24 13:10 UTC, sduenas commented on tests/test_schema.py
> +                                                        tzinfo=dateutil.tz.tzutc()))
We can remove some data that is not really needed on the test to make it easier to read.

2021-02-24 13:10 UTC, sduenas commented on tests/test_schema.py
> +                                individual=indv)
This can be removed too.

2021-02-24 13:10 UTC, sduenas commented on tests/test_schema.py
> +        self.assertEqual(rol2['end'], '2100-01-01T00:00:00+00:00')
This is not needed for the test.

2021-02-24 13:10 UTC, sduenas commented on tests/test_schema.py
> +SH_INDIVIDUALS_BOT_FILTER = """{
We should reduce the data that is requested in this query to make the test easier to read and understand it. We only need `mk` and `isBot` fields.

2021-02-24 13:10 UTC, sduenas commented on ui/src/components/Search.vue
> +          } else if (text === "false") {
What happens if the `text` is `"true"`?

2021-02-24 15:20 UTC, evamillan commented
@sduenas Thanks for the feedback. I removed the unnecessary data and added a case for when the search text is "true".

2021-02-24 17:51 UTC, sduenas commented on tests/test_schema.py
> +  individuals(filters: {isBot: true}) {
We should also test this for a `false` case.

2021-02-24 17:51 UTC, sduenas requested changes
I've been testing this patch using the UI and I don't get any error when I set invalid values for `isBot`. It always returns identities that are not bots. On the other hand, if I use the graphql API I get errors.

```
query individuals {
  individuals(filters: { lastUpdated:">=2020-11-25T18:04:38.000Z", isBot:"falsee" }) {
    entities {
      mk
      lastModified
    }
  }
}

{
  "errors": [
    {
      "message": "Argument \"filters\" has invalid value {lastUpdated: \">=2020-11-25T18:04:38.000Z\", isBot: \"falsee\"}.\nIn field \"isBot\": Expected type \"Boolean\", found \"falsee\".",
      "locations": [
        {
          "line": 2,
          "column": 24
        }
      ],
      "extensions": {
        "code": 128
      }
    }
  ]
}
```

Can you check it, please?

2021-02-25 10:24 UTC, evamillan commented
> I've been testing this patch using the UI and I don't get any error when I set invalid values for `isBot`. It always returns identities that are not bots. On the other hand, if I use the graphql API I get errors.

@sduenas It looks like it converts the string to a boolean automatically when you query from the UI, but I can't find why it does that or how to prevent it. I've changed it so that it shows an error on the UI if the value is invalid and stops it from searching. Does this solution work for you?

2021-02-25 17:37 UTC, sduenas commented
> > I've been testing this patch using the UI and I don't get any error when I set invalid values for `isBot`. It always returns identities that are not bots. On the other hand, if I use the graphql API I get errors.
> 
> @sduenas It looks like it converts the string to a boolean automatically when you query from the UI, but I can't find why it does that or how to prevent it. I've changed it so that it shows an error on the UI if the value is invalid and stops it from searching. Does this solution work for you?

I've been tracing the source of the problem. Python `graphene` doesn't parse correctly `string` values for `Boolean` fields. It uses `bool(value)` to cast to a boolean value but this is wrong because it always returns `True` for string values.
Your proposed solution is valid for us.

2021-02-25 17:37 UTC, sduenas approved these changes

2021-02-25 17:39 UTC, merged