[ui] Add logging messages
chaoss/grimoirelab-sortinghat pull request #482
Opened 2021-03-16 10:34 UTC by evamillan

Logs a message to the console when the following operations are performed, including the values that were changed:
- Add identity
- Move identity
- Update profile
- Enroll in organization
- Update enrollment
- Remove enrollment
- Merge identities
- Split identities
- Delete identity
- Add organization
- Add domain
- Remove domain
- Log in/out

The logs are not shown in production mode (when running `yarn serve --mode production`, for example).

2021-03-16 11:48 UTC, sduenas requested changes
In overall the PR looks good to me but it needs some changes. For example, I think all `log` messages should be set to `debug` (I added some comments about it). Also, please rebase the PR because is failing due `flake8`checks that we already fixed in a previous commit.

2021-03-16 11:48 UTC, sduenas commented on ui/src/App.vue
> +      this.$logger.log(`Log out user ${this.user}`);
Set is as `info`.

2021-03-16 11:48 UTC, sduenas commented on ui/src/components/IndividualsTable.vue
> +        this.$logger.log(
Set it as `debug` message.

2021-03-16 11:48 UTC, sduenas commented on ui/src/plugins/logger.js
> +        return;
I think for production we might want all messages but `debug` ones. If the app is reporting an error, users can give us useful information.

2021-03-16 11:48 UTC, sduenas commented on ui/src/plugins/logger.js
> +    Vue.prototype.$logger = {
We need some unit tests for this. For example, they can test the message is correctly written or that the log level is correctly set depending on the function called.

2021-03-17 11:12 UTC, evamillan commented
I updated the PR adding tests and replacing the `log` messages with `debug`.

2021-03-18 09:34 UTC, sduenas approved these changes
LGTM

2021-03-18 09:39 UTC, merged