[core] Fix deprecated class
chaoss/grimoirelab-sortinghat pull request #527
Opened 2021-04-17 15:33 UTC by VSevagen

django_mysql.models.JSONField is deprecated. I replaced it
with the equivalent provided through the log

Signed-off-by: sevagenv <sevagenv@gmail.com>

2021-04-17 16:27 UTC, VSevagen commented
@sduenas It seems like django.db.models.JSONField is not available in Django 2.1. It was added from django 3.1. Also, in the requirements.txt file, there is a mismatch with django-mysql and django version. django-mysql does not support django2.1. django should be >=2.2
Should I bump django to 3.1 or just leave it as it is ? i think it is the current django version that is causing an issue.

2021-04-19 12:22 UTC, sduenas commented
I won't have any problem to upgrade the code to Django 3.1. It would be better. My only concern is that the related libraries such as `graphene-django`, `django-rq`, etc, are compatible with this version of Django. If they are, go ahead and update the PR.

2021-04-19 18:25 UTC, VSevagen commented
I updated the requirements. Only `mysqlclient` has issue with django, updated that and for `django-mysql`, the latest version is currently 3.11.1

2021-04-20 08:39 UTC, VSevagen commented
The exceptions are being raised but the error messages do not match. The easy fix wouldd be to modify `INVALID_BOOLEAN_CHECK_ERROR` but I doubt this is the proper way of fixing this issue.

2021-04-24 09:08 UTC, VSevagen commented
> The exceptions are being raised but the error messages do not match. The easy fix wouldd be to modify `INVALID_BOOLEAN_CHECK_ERROR` but I doubt this is the proper way of fixing this issue.

I checked whether any dependency was causing this issue. Turns out its Django. Keeping all the other deps changes as they are, the issue arises when I transition from django2.2 to >=django3.0. It seems that the validation error message is shown in a list or dict format from django 3.0 onwards.

2021-06-15 10:33 UTC, sduenas requested changes
LGTM but I think we should remove the dependency with `django-mysql`.

2021-06-16 08:50 UTC, VSevagen commented on requirements.txt
> +django-mysql>=3.11.1
I removed it in pyproject.toml as well.

2021-06-16 17:44 UTC, sduenas requested changes
Thanks for your changes but I forgot to mention to update the README file. It has references to Django version and this django-mysql package.

2021-06-17 11:15 UTC, sduenas approved these changes
LGTM

2021-06-17 11:19 UTC, sduenas commented
@VSevagen I saw there's some problems with your branch. It's not rebased propertly. Would you mind to fix it?

2021-06-17 13:53 UTC, VSevagen commented
@sduenas I rebased it.

2021-06-18 09:29 UTC, sduenas approved these changes
LGTM

2021-06-18 09:29 UTC, merged

2021-06-18 09:29 UTC, sduenas commented
Thanks for your contribution @VSevagen .