[tests] Improve coverage for schema.py
chaoss/grimoirelab-sortinghat pull request #533
Opened 2021-04-25 14:39 UTC by VSevagen

Tests were missing for handling invalid datetime
values for enrollment_date and for some operators
in last_updated filter.

Signed-off-by: sevagenv <sevagenv@gmail.com>

2021-04-28 21:57 UTC, sduenas requested changes
Looks good but just some minor changes need to be addressed before merging it. These changes are needed to follow the code style we have in the project.

2021-04-28 21:57 UTC, sduenas commented on tests/test_schema.py
> +        expected_error = 'Upper bound must be greater than the lower bound'
To keep the consistency on the style, please put long strings between double quotes.

2021-04-28 21:57 UTC, sduenas commented on tests/test_schema.py
> +      """ Check whether it fails when the filter has an invalid date """
Remove the leading and trailing spaces from the docstring.

2021-04-29 04:42 UTC, VSevagen commented
@sduenas I've updated the PR.

2021-04-29 10:05 UTC, sduenas approved these changes
LGTM

2021-04-29 11:06 UTC, VSevagen commented
My bad, I forgot to run flake locally before pushing :sweat_smile: 
I updated it properly this time.

2021-04-29 11:36 UTC, sduenas commented
> My bad, I forgot to run flake locally before pushing sweat_smile
> I updated it properly this time.

Can you rebase it before I merge it?

2021-06-04 15:24 UTC, sduenas approved these changes
LGTM

2021-06-04 15:30 UTC, merged