Gender recommendations
chaoss/grimoirelab-sortinghat pull request #556
Opened 2021-07-02 10:58 UTC by evamillan

This PR adds a `recommendGender` mutation, which returns a job with a possible gender for each given individual uuid based on their profile name. The recommendations are provided by the genderize.io API.

Example of the mutation:
```
mutation {
  recommendGender(uuids: ["uuid"], apiToken: "token") {
    jobId
  }
}
```
Example of the job query:
```
query {
  job(jobId: "id") {
    jobId
    status
    jobType
    result {
      __typename
      ... on GenderRecommendationType {
          uuid
          gender
	  accuracy
      }
    }
    errors
  }
}
```

The individuals' genders can be autocompleted using these same recommendations with the `autogender` mutation.
Example of the mutation:
```
mutation {
  autogender(uuids:["uuid1", "uuid2"], apiToken: "token") {
    jobId
  }
}
```
Example of the job result query:
```
query {
  job(jobId: "id") {
    status
    jobType
    result {
      ... on AutogenderResultType {
        uuid
        gender
        accuracy
      }
    }
    errors
  }
}
```
Closes #471.

2021-07-05 07:57 UTC, sduenas requested changes
The PR in overall looks great but some changes are needed. Also, it would be great if some of the tests that we have on the original code can be added too. For example, [test_retry](https://github.com/chaoss/grimoirelab-sortinghat/blob/master/tests/test_cmd_autogender.py#L395).

2021-07-05 07:57 UTC, sduenas commented on tests/test_jobs.py
> +import httpretty
`httpretty` is a third party library. We usually leave a blank line between standard libraries and third-party ones.

2021-07-05 07:57 UTC, sduenas commented on sortinghat/core/jobs.py
> +def recommend_gender(ctx, uuids, api_token=None):
I think the API token should be defined in the configuration of SortingHat instead of giving it in the call.

2021-07-05 07:57 UTC, sduenas commented on tests/rec/test_gender.py
> +    def test_not_found_individual(self):
I think that this test should be also included in the tests for the mutations so we can check that everything goes ok.

2021-07-05 07:57 UTC, sduenas commented on sortinghat/core/jobs.py
> +def autogender(ctx, uuids=None, api_token=None):
I never liked this name. I think we should use `genderize` (which is linked to the service we use).

2021-07-05 15:02 UTC, evamillan commented
I updated the PR with the changes you requested.

2021-07-06 07:09 UTC, sduenas commented on tests/rec/test_gender.py
> +    def test_not_found_individual(self):
We finally decided this wasn't needed because during the mutation tests we mock the response, so this function is not going to fail.

2021-07-06 07:20 UTC, sduenas requested changes
Good job. Just minor changes and please, can you squash some of the commits that have the same functionality?

2021-07-06 07:20 UTC, sduenas commented on sortinghat/core/recommendations/gender.py
> +from django.conf import settings
I would move this inside `_genderize` function and get the `GENDERIZE_API_KEY` only there. That will mean that the key will be read again if it's updated, so we won't need to restart the system again if the file changes. Also, the value of the key in memory will be (or should be) destroyed once the function is done.

2021-07-06 07:20 UTC, sduenas commented on sortinghat/core/recommendations/gender.py
> +api_key = settings.GENDERIZE_API_KEY
Can we change the name of the setting to `SORTINGHAT_GENDERIZE_API_KEY`? I start thinking we should use `SORTINGHAT_` prefix with all the SortingHat settings to differentiate them from the rest of the settings.

2021-07-06 17:35 UTC, sduenas commented on sortinghat/core/recommendations/gender.py
> +from django.conf import settings
See my suggestion below. You can delete his line from above.

2021-07-06 17:36 UTC, sduenas commented on sortinghat/core/recommendations/gender.py
> +    api_key = settings.SORTINGHAT_GENDERIZE_API_KEY
```suggestion
    from django.conf import settings
    
    api_key = settings.SORTINGHAT_GENDERIZE_API_KEY
```

2021-07-07 08:46 UTC, sduenas approved these changes
LGTM

2021-07-07 09:00 UTC, merged